services:
  lab3:
    image: ubuntu:24.04
    container_name: lab3
    tty: true
    stdin_open: true
    privileged: true
    environment:
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: ["/workspace/setup.sh"]
